# Generated by Django 5.2.7 on 2025-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='website',
        ),
        migrations.AddField(
            model_name='shop',
            name='source_file',
            field=models.CharField(blank=True, help_text='Относительный путь к файлу (например, data/shop1.yaml)', max_length=500, null=True, verbose_name='Путь к файлу источника'),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Статус получения заказов'),
        ),
    ]
