# Generated by Django 5.2.7 on 2025-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_shop_website_shop_source_file_shop_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['user', 'city', 'street', 'house'], 'verbose_name': 'Контакты пользователя', 'verbose_name_plural': 'Список контактов пользователя'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=15, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=15, verbose_name='Строение'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='Город не указан', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default='Улица не указана', max_length=100, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=15, verbose_name='Корпус'),
        ),
    ]
