# Generated by Django 5.2.7 on 2025-11-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['user', 'user__last_name', 'user__first_name'], 'verbose_name': 'Контакт пользователя', 'verbose_name_plural': 'Список контактов пользователя'},
        ),
    ]
