# Generated by Django 5.2.7 on 2025-11-14 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Контакт подтверждён'),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.CreateModel(
            name='ContactConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_token', to='backend.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Подтверждение контакта',
                'verbose_name_plural': 'Подтверждения контактов',
            },
        ),
    ]
