# Generated by Django 5.2.7 on 2025-12-08 09:45

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_contact_options_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_view',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/details', verbose_name='Детальная картинка товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/originals', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='products/thumbs', verbose_name='Миниатюра товара'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars/thumbnails', verbose_name='Аватар-миниатюра'),
        ),
        migrations.AddField(
            model_name='user',
            name='original_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/originals', verbose_name='Аватар'),
        ),
    ]
